# Generated by Django 2.1.3 on 2018-11-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envmodel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envinfo',
            name='ip',
        ),
        migrations.AddField(
            model_name='envinfo',
            name='IP',
            field=models.CharField(default='www.baiud.com', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envinfo',
            name='Registry',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
