# Generated by Django 2.1.3 on 2018-11-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envmodel', '0002_auto_20181128_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='envinfo',
            name='Name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
